"""
src/report/builder.py
=====================
HTML report builder for the AI Strategic Briefing pipeline.

Produces a single self-contained HTML file with:
- An AI executive briefing section (or a placeholder if no API key is set)
- A 12-month Holt-Winters forecast chart (Chart.js 4, if time-series data)
- An anomaly table (if anomalies were detected)
- Per-column statistics cards (rendered via embedded JS from inline JSON)

All data (stats, forecast, anomalies) is embedded as JSON in a <script> block,
making the output file fully portable — no server, no build step required.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional


HTML_TEMPLATE: str = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{TITLE}} — Strategic Briefing</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f0f0f; color: #e5e5e5; font-size: 14px; line-height: 1.6; padding: 40px 20px; }
  .container { max-width: 960px; margin: 0 auto; }
  .report-header { border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 24px; margin-bottom: 32px; }
  .report-title { font-size: 24px; font-weight: 700; letter-spacing: -0.3px; margin-bottom: 6px; }
  .report-meta { font-size: 12px; color: #606060; font-family: monospace; }
  .section { margin-bottom: 36px; }
  .section-label { font-size: 10px; font-family: monospace; text-transform: uppercase; letter-spacing: 0.12em; color: #606060; margin-bottom: 12px; }
  .ai-brief { background: #161616; border: 1px solid rgba(232,160,32,0.2); border-left: 3px solid #E8A020; border-radius: 8px; padding: 20px 24px; font-size: 13px; color: #c0c0c0; line-height: 1.75; white-space: pre-wrap; }
  .stats-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 10px; }
  .stat-card { background: #161616; border: 1px solid rgba(255,255,255,0.07); border-radius: 8px; padding: 14px; }
  .stat-name { font-size: 11px; font-family: monospace; color: #606060; margin-bottom: 8px; }
  .stat-row { display: flex; justify-content: space-between; font-size: 12px; padding: 2px 0; }
  .stat-key { color: #808080; }
  .stat-val { color: #e5e5e5; font-family: monospace; }
  .outlier-warn { color: #f87171; }
  .chart-card { background: #161616; border: 1px solid rgba(255,255,255,0.07); border-radius: 10px; padding: 20px; margin-bottom: 16px; }
  .chart-title { font-size: 13px; font-weight: 600; margin-bottom: 4px; }
  .chart-sub { font-size: 11px; color: #808080; margin-bottom: 16px; }
  .chart-wrap { position: relative; height: 240px; }
  .anomaly-table { width: 100%; border-collapse: collapse; font-size: 12px; }
  .anomaly-table th { font-family: monospace; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #606060; padding: 8px 12px; border-bottom: 1px solid rgba(255,255,255,0.07); text-align: left; }
  .anomaly-table td { padding: 8px 12px; border-bottom: 1px solid rgba(255,255,255,0.04); color: #a0a0a0; }
  .sev-high { color: #f87171; font-weight: 600; }
  .sev-medium { color: #fbbf24; font-weight: 600; }
  .sev-low { color: #4ade80; font-weight: 600; }
  .kpi-row { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 10px; margin-bottom: 20px; }
  .kpi { background: #161616; border: 1px solid rgba(255,255,255,0.07); border-radius: 8px; padding: 14px; }
  .kpi-label { font-size: 10px; font-family: monospace; color: #606060; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; }
  .kpi-value { font-size: 20px; font-weight: 700; color: #e5e5e5; }
  .kpi-sub { font-size: 11px; color: #808080; margin-top: 3px; }
  footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid rgba(255,255,255,0.06); font-size: 11px; color: #505050; }
</style>
</head>
<body>
<div class="container">
  <div class="report-header">
    <div class="report-title">{{TITLE}}</div>
    <div class="report-meta">Strategic Briefing · Generated {{DATE}} · {{N_ROWS}} records · {{N_COLS}} fields</div>
  </div>

  {{AI_SECTION}}

  {{FORECAST_SECTION}}

  {{ANOMALY_SECTION}}

  <div class="section">
    <div class="section-label">Column Statistics</div>
    <div class="stats-grid" id="statsGrid"></div>
  </div>

  <footer>
    Generated by <strong>AI Strategic Briefing Generator</strong> · <a href="https://akbknight.github.io" style="color:#808080">akbknight.github.io</a>
    · Source: {{SOURCE_FILE}}
  </footer>
</div>

<script>
const STATS = {{STATS_JSON}};
const FORECAST = {{FORECAST_JSON}};
const ANOMALIES = {{ANOMALIES_JSON}};

function esc(s) { const d = document.createElement('div'); d.textContent = String(s); return d.innerHTML; }

function renderStats() {
  const grid = document.getElementById('statsGrid');
  STATS.forEach(s => {
    const card = document.createElement('div');
    card.className = 'stat-card';
    card.appendChild(Object.assign(document.createElement('div'), { className: 'stat-name', textContent: s.column }));
    const rows = [
      ['mean', s.mean], ['median', s.median], ['std', s.std],
      ['min', s.min], ['max', s.max], ['missing', s.missing_pct + '%'],
      ['outliers (z)', s.outliers_zscore], ['outliers (IQR)', s.outliers_iqr],
    ];
    rows.forEach(([k, v]) => {
      const row = document.createElement('div');
      row.className = 'stat-row';
      const keyEl = Object.assign(document.createElement('span'), { className: 'stat-key', textContent: k });
      const valEl = Object.assign(document.createElement('span'), { className: 'stat-val' + (k.startsWith('outlier') && v > 0 ? ' outlier-warn' : ''), textContent: String(v) });
      row.appendChild(keyEl);
      row.appendChild(valEl);
      card.appendChild(row);
    });
    grid.appendChild(card);
  });
}

function renderForecast() {
  if (!FORECAST) return;
  const canvas = document.getElementById('forecastCanvas');
  if (!canvas) return;
  new Chart(canvas.getContext('2d'), {
    type: 'line',
    data: {
      labels: [...FORECAST.history_dates.slice(-48), ...FORECAST.forecast_dates].map(d => {
        const dt = new Date(d); return dt.toLocaleDateString('en-US', {year:'numeric',month:'short'});
      }),
      datasets: [
        { label: FORECAST.value_col + ' (actual)', data: [...FORECAST.history_values.slice(-48), ...new Array(FORECAST.forecast_point.length).fill(null)], borderColor: '#E8A020', borderWidth: 1.5, pointRadius: 0, tension: 0.3, fill: false },
        { label: 'Forecast', data: [...new Array(48).fill(null), ...FORECAST.forecast_point], borderColor: '#60a5fa', borderWidth: 1.5, borderDash: [4,3], pointRadius: 0, tension: 0.3, fill: false },
        { label: '95% CI upper', data: [...new Array(48).fill(null), ...FORECAST.ci95u], borderColor: 'rgba(96,165,250,0.15)', backgroundColor: 'rgba(96,165,250,0.08)', borderWidth: 0, pointRadius: 0, fill: '+1' },
        { label: '95% CI lower', data: [...new Array(48).fill(null), ...FORECAST.ci95l], borderColor: 'rgba(96,165,250,0.15)', borderWidth: 0, pointRadius: 0, fill: false },
      ]
    },
    options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#606060', font: { size: 10 }, maxTicksLimit: 10, maxRotation: 0 }, grid: { color: 'rgba(255,255,255,0.03)' }, border: { display: false } }, y: { ticks: { color: '#606060', font: { size: 10 } }, grid: { color: 'rgba(255,255,255,0.03)' }, border: { display: false } } } }
  });
}

renderStats();
renderForecast();
</script>
</body>
</html>"""


def build_report(
    title: str,
    profile: dict,
    col_stats: list,
    forecast: Optional[dict],
    anomalies: list,
    ai_summary: str,
    source_file: str,
) -> str:
    """Assemble a self-contained HTML report from pipeline outputs.

    All data is embedded as inline JSON in a <script> block.  The template
    string is populated via simple string substitution (no external templating
    dependency).

    Parameters
    ----------
    title : str
        Report title displayed in the header and browser tab.
    profile : dict
        Output of ``load_and_profile()``.
    col_stats : list
        Output of ``compute_stats()``.
    forecast : dict | None
        Output of ``run_forecast()``, or None.
    anomalies : list
        Output of ``detect_anomalies_in_series()``, or empty list.
    ai_summary : str
        Narrative text from ``generate_ai_summary()``, or empty string.
    source_file : str
        Original CSV path (only the filename is shown in the footer).

    Returns
    -------
    str
        Complete HTML document as a string.
    """
    date_str: str = datetime.now().strftime("%Y-%m-%d %H:%M")
    html: str = HTML_TEMPLATE

    # ── Header substitutions ─────────────────────────────────────────────────
    html = html.replace("{{TITLE}}", title)
    html = html.replace("{{DATE}}", date_str)
    html = html.replace("{{N_ROWS}}", str(profile["n_rows"]))
    html = html.replace("{{N_COLS}}", str(profile["n_cols"]))
    html = html.replace("{{SOURCE_FILE}}", Path(source_file).name)

    # ── AI narrative section ─────────────────────────────────────────────────
    if ai_summary:
        ai_html = (
            '<div class="section">'
            '<div class="section-label">AI Executive Briefing</div>'
            f'<div class="ai-brief">{ai_summary}</div>'
            "</div>"
        )
    else:
        ai_html = (
            '<div class="section">'
            '<div class="section-label">Executive Briefing</div>'
            '<div class="ai-brief" style="border-color:rgba(255,255,255,0.1);'
            'border-left-color:#808080">'
            "Set ANTHROPIC_API_KEY to enable AI-generated executive insights."
            "</div></div>"
        )
    html = html.replace("{{AI_SECTION}}", ai_html)

    # ── Forecast section ─────────────────────────────────────────────────────
    if forecast:
        change_color: str = "#4ade80" if forecast["change_pct"] >= 0 else "#f87171"
        change_sign: str = "+" if forecast["change_pct"] >= 0 else ""
        forecast_html = (
            f'<div class="section">'
            f'<div class="section-label">12-Month Forecast — {forecast["value_col"]}</div>'
            f'<div class="kpi-row">'
            f'<div class="kpi"><div class="kpi-label">Latest</div>'
            f'<div class="kpi-value">{forecast["latest"]}</div>'
            f'<div class="kpi-sub">{forecast["latest_date"]}</div></div>'
            f'<div class="kpi"><div class="kpi-label">12m Forecast</div>'
            f'<div class="kpi-value">{forecast["forecast_12m"]}</div>'
            f'<div class="kpi-sub">{forecast["forecast_12m_date"]}</div></div>'
            f'<div class="kpi"><div class="kpi-label">Projected Change</div>'
            f'<div class="kpi-value" style="color:{change_color}">'
            f'{change_sign}{forecast["change_pct"]}%</div>'
            f'<div class="kpi-sub">Holt-Winters ETS</div></div>'
            f'<div class="kpi"><div class="kpi-label">RMSE</div>'
            f'<div class="kpi-value">{forecast["rmse"]}</div>'
            f'<div class="kpi-sub">In-sample fit</div></div>'
            f"</div>"
            f'<div class="chart-card">'
            f'<div class="chart-title">{forecast["value_col"]} — History + 12-Month Forecast</div>'
            f'<div class="chart-sub">Holt-Winters additive trend + seasonality · AIC {forecast["aic"]}</div>'
            f'<div class="chart-wrap"><canvas id="forecastCanvas"></canvas></div>'
            f"</div></div>"
        )
    else:
        forecast_html = ""
    html = html.replace("{{FORECAST_SECTION}}", forecast_html)

    # ── Anomaly section ──────────────────────────────────────────────────────
    if anomalies:
        rows: str = ""
        for anomaly in anomalies[:20]:
            sev_cls: str = f"sev-{anomaly['severity']}"
            rows += (
                f"<tr>"
                f"<td style='font-family:monospace'>{anomaly['date']}</td>"
                f"<td>{anomaly['value']}</td>"
                f"<td class='{sev_cls}'>{anomaly['severity']}</td>"
                f"<td style='font-family:monospace;color:#606060'>{anomaly['type']}</td>"
                f"<td style='color:#808080'>{anomaly['score']}&sigma;</td>"
                f"</tr>"
            )
        anomaly_html = (
            f'<div class="section">'
            f'<div class="section-label">{len(anomalies)} Anomalies Detected</div>'
            f'<div class="chart-card" style="padding:0">'
            f'<table class="anomaly-table">'
            f"<thead><tr><th>Date</th><th>Value</th><th>Severity</th>"
            f"<th>Method</th><th>Score</th></tr></thead>"
            f"<tbody>{rows}</tbody>"
            f"</table></div></div>"
        )
    else:
        anomaly_html = ""
    html = html.replace("{{ANOMALY_SECTION}}", anomaly_html)

    # ── Embedded JSON data ───────────────────────────────────────────────────
    html = html.replace("{{STATS_JSON}}", json.dumps(col_stats))
    html = html.replace("{{FORECAST_JSON}}", json.dumps(forecast) if forecast else "null")
    html = html.replace("{{ANOMALIES_JSON}}", json.dumps(anomalies))

    return html
